# Podfile

platform :ios, '6.0'

target "InstagramSDK" do
	pod 'Typhoon', :head
    pod "AFNetworking", "~> 2.0"
end

target :InstagramSDKTests, :exclusive => true do
    pod 'Kiwi/XCTest'
    pod 'Nocilla'
end