# Podfile
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'InstagramSDK' do
    pod 'AFNetworking', '~> 2.4'
    pod 'Typhoon'
end

target :InstagramSDKTests, :exclusive => true do
    pod 'Kiwi'
    pod 'Nocilla'
end